apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::908457663042:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EPI6RFXX9BCI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::908457663042:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-13T18:55:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9426"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b9bc2afc-12b8-449e-8f69-352050fc8ce5
